### ISSUE TITLE
Angular Universal: Syntax Error

### ISSUE THREAD

**Issue by logan-jobzmall** [opendecide/ngx-segment-analytics#93]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
Mac OS Mojave 10.14.5

### Tools Version
Node: 10.15.3
Yarn: 1.13.0

### Targeted Angular version
8.2.3

### Setup

**Angular.json:**
```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "cli": {
    "defaultCollection": "@ngrx/schematics",
    "packageManager": "yarn"
  },
  "projects": {
    "app": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {
        "@schematics/angular:module": {
          "spec": false
        },
        "@schematics/angular:component": {
          "styleext": "scss"
        },
        "@ngrx/schematics:component": {
          "styleext": "scss"
        },
        "@ngrx/schematics:container": {
          "styleext": "scss"
        }
      },
      "architect": {
        "build": {
          "builder": "udk:udk-builder",
          "options": {
            "browserTarget": "app:browser",
            "serverTarget": "app:server"
          },
          "configurations": {
            "production": {
              "browserTarget": "app:browser",
              "serverTarget": "app:server:spa"
            },
            "spa": {
              "browserTarget": "app:browser",
              "serverTarget": "app:server:spa"
            }
          }
        },
        "browser": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/app/browser",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "assets": [
              "src/manifest.json",
              "src/assets/videos",
              "src/assets/images",
              "src/assets/sounds",
              {
                "glob": "**/*",
                "input": "src/assets/",
                "output": "/assets/"
              },
              {
                "glob": "favicon.ico",
                "input": "src",
                "output": "/"
              },
              "src/assets/data",
              "src/assets/i18n",
              "src/assets/config.local.json"
            ],
            "stylePreprocessorOptions": {
              "includePaths": [
                "src/assets/sass"
              ]
            },
            "styles": [
              
            ],
            "scripts": [
              
            ],
            "progress": true
          },
          "configurations": {
            "dev": {
              "fileReplacements": [{
                "replace": "src/environments/environment.ts",
                "with": "src/environments/environment.dev.ts"
              }]
            },
            "qa": {
              "fileReplacements": [{
                "replace": "src/environments/environment.ts",
                "with": "src/environments/environment.qa.ts"
              }],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            },
            "production": {
              "fileReplacements": [{
                "replace": "src/environments/environment.ts",
                "with": "src/environments/environment.prod.ts"
              }],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            }
          }
        },
        "server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist/app/server",
            "main": "src/server.ts",
            "tsConfig": "tsconfig.server.json",
            "progress": true,
            "sourceMap": {
              "scripts": true,
              "styles": false
            },
            "stylePreprocessorOptions": {
              "includePaths": [
                "src/assets/sass"
              ]
            }
          },
          "configurations": {
            "dev": {
              "fileReplacements": [{
                "replace": "src/environments/environment.ts",
                "with": "src/environments/environment.dev.ts"
              }]
            },
            "qa": {
              "fileReplacements": [{
                "replace": "src/environments/environment.ts",
                "with": "src/environments/environment.qa.ts"
              }],
              "outputHashing": "media"
            },
            "production": {
              "fileReplacements": [{
                "replace": "src/environments/environment.ts",
                "with": "src/environments/environment.prod.ts"
              }],
              "outputHashing": "media"
            },
            "spa": {
              "fileReplacements": [{
                "replace": "src/app/app-routes.ts",
                "with": "src/app/app-routes.spa.ts"
              }]
            }
          }
        },
        "serve": {
          "builder": "udk:udk-runner",
          "options": {},
          "configurations": {}
        },
        "serve-spa": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "app:browser"
          },
          "configurations": {
            "production": {
              "browserTarget": "app:browser:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "app:browser"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "tsconfig.json",
              "tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "app"
}
```

Then I just run: `yarn build && node --max-old-space-size=8192 ./dist/app/server/main.js`

### The log given by the failure.
```
(function (exports, require, module, __filename, __dirname) { import { Inject, Injectable, InjectionToken, NgModule, Optional, PLATFORM_ID, SkipSelf } from '@angular/core';
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

### Workaround?
This happens in Angular 7 as well as 8. I have changed builders as well. The only thing that helped with this was to create a postinstall and babel the package `babel node_modules/ngx-segment-analytics -d node_modules/ngx-segment-analytics --presets @babel/preset-env`.

This seems really bad, and like something is wrong. Trying to find the right direction here. Thank you!

**Comment by guillaume-ro-fr** [comment]
Hi @logan-jobzmall  !

Thanks for the report. A new release is available (1.5.0), can you test it ?
Thank you.

**Comment by logan-jobzmall** [comment]
Hi @guillaume-ro-fr - Very sorry for such a late reply. I am finally working with Segment in Angular Universal again, and this doesn't seem to be a problem anymore.

**Comment by guillaume-ro-fr** [comment]
@logan-jobzmall No problem, Thanks for your answer !
